# Generated by Django 3.0.6 on 2023-12-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConfiguracionApp', '0001_initial'),
        ('SolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosclie',
            name='IdSolicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.Solicitud'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='IdTasaInte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.TasaInte'),
        ),
    ]
