# Generated by Django 3.0.6 on 2023-12-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SolicitudesApp', '0001_initial'),
        ('ConfiguracionApp', '0002_auto_20231222_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionJuraCli',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NombrePersNat', models.CharField(max_length=60)),
                ('DuiPersNat', models.CharField(max_length=12)),
                ('NumeroCred', models.CharField(max_length=20)),
                ('Monto', models.CharField(max_length=30)),
                ('Plazo', models.CharField(max_length=20)),
                ('Cuota', models.CharField(max_length=30)),
                ('FormaPago', models.CharField(max_length=20)),
                ('CanceladoAcueCuo', models.CharField(max_length=5)),
                ('RealizarPagoAdi', models.CharField(max_length=5)),
                ('ProcedenciaFond', models.CharField(max_length=40, null=True)),
                ('IdSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.Solicitud')),
                ('IdTipoOper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.TipoOper')),
            ],
            options={
                'verbose_name': 'DeclaracionJuraCli',
                'verbose_name_plural': 'DeclaracionJuraClis',
                'db_table': 'DeclaracionJuraCli',
            },
        ),
        migrations.CreateModel(
            name='DeclaracionJiroNeg',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Empresa', models.CharField(max_length=50, null=True)),
                ('IndustriaDe', models.CharField(max_length=50, null=True)),
                ('ComercioDe', models.CharField(max_length=50, null=True)),
                ('EspecificarOtro', models.CharField(max_length=40, null=True)),
                ('IdDeclaracionJuraCli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeclaracionJurClienteApp.DeclaracionJuraCli')),
            ],
            options={
                'verbose_name': 'DeclaracionJiroNeg',
                'verbose_name_plural': 'DeclaracionJiroNegs',
                'db_table': 'DeclaracionJiroNeg',
            },
        ),
        migrations.CreateModel(
            name='DeclaracionActiEco',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('EmpleadoEn', models.CharField(max_length=50)),
                ('ProfecionalInde', models.CharField(max_length=50, null=True)),
                ('ConocimientosEn', models.CharField(max_length=50, null=True)),
                ('EmpresarioEn', models.CharField(max_length=50, null=True)),
                ('EspecificarOtraAct', models.CharField(max_length=50, null=True)),
                ('IdDeclaracionJuraCli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeclaracionJurClienteApp.DeclaracionJuraCli')),
            ],
            options={
                'verbose_name': 'DeclaracionActiEco',
                'verbose_name_plural': 'DeclaracionActiEcos',
                'db_table': 'DeclaracionActiEco',
            },
        ),
    ]
