# Generated by Django 3.0.6 on 2023-12-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SolicitudesApp', '0001_initial'),
        ('ConfiguracionApp', '0002_auto_20231222_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoViviDatGen',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('TiempoCons', models.CharField(max_length=10)),
                ('Modelo', models.CharField(max_length=30)),
                ('DimensionVivi', models.CharField(max_length=50)),
                ('CantidadVivi', models.IntegerField()),
                ('CostoTotaViv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IdSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.Solicitud')),
            ],
            options={
                'verbose_name': 'PresupuestoViviDatGen',
                'verbose_name_plural': 'PresupuestoViviDatGens',
                'db_table': 'PresupuestoViviDatGen',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoViviDatGenObr',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('TipoObra', models.CharField(max_length=100)),
                ('CostoObra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SolucionSan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TotalObraAdi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IdPresupuestoViviDatGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PresupuestoVApp.PresupuestoViviDatGen')),
            ],
            options={
                'verbose_name': 'PresupuestoViviDatGenObr',
                'verbose_name_plural': 'PresupuestoViviDatGenObrs',
                'db_table': 'PresupuestoViviDatGenObr',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoViviTot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Materiales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ManoObra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Transporte', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SolucionSani', models.DecimalField(decimal_places=2, max_digits=15)),
                ('KitEmer', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Herramientas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TotalCostDir', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IdPresupuestoViviDatGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PresupuestoVApp.PresupuestoViviDatGen')),
            ],
            options={
                'verbose_name': 'PresupuestoViviTot',
                'verbose_name_plural': 'PresupuestoViviTots',
                'db_table': 'PresupuestoViviTot',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoViviMatObr',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PrecioUnit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SubTota', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IdMateriales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.Materiales')),
                ('IdPresupuestoViviDatGenObr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PresupuestoVApp.PresupuestoViviDatGenObr')),
            ],
            options={
                'verbose_name': 'PresupuestoViviMatObr',
                'verbose_name_plural': 'PresupuestoViviMatObrs',
                'db_table': 'PresupuestoViviMatObr',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoViviMat',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PrecioUnit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SubTota', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IdMateriales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.Materiales')),
                ('IdPresupuestoViviDatGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PresupuestoVApp.PresupuestoViviDatGen')),
            ],
            options={
                'verbose_name': 'PresupuestoViviMat',
                'verbose_name_plural': 'PresupuestoViviMats',
                'db_table': 'PresupuestoViviMat',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoViviManObrObr',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Unidad', models.CharField(max_length=10)),
                ('PrecioUnit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SubTota', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IdPresupuestoViviDatGenObr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PresupuestoVApp.PresupuestoViviDatGenObr')),
            ],
            options={
                'verbose_name': 'PresupuestoViviManObrObr',
                'verbose_name_plural': 'PresupuestoViviManObrObrs',
                'db_table': 'PresupuestoViviManObrObr',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoViviManObr',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Unidad', models.CharField(max_length=10)),
                ('PrecioUnit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SubTota', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IdPresupuestoViviDatGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PresupuestoVApp.PresupuestoViviDatGen')),
            ],
            options={
                'verbose_name': 'PresupuestoViviManObr',
                'verbose_name_plural': 'PresupuestoViviManObrs',
                'db_table': 'PresupuestoViviManObr',
            },
        ),
    ]
