# Generated by Django 3.0.6 on 2024-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConozcaClienteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientedatogen',
            name='ProfesionDui',
            field=models.CharField(max_length=50),
        ),
    ]
